[package]
name = "li-watch"
version = "0.0.1"
edition = "2026"
license = "Apache-2.0 OR MIT"
description = "Reflector/informer cache for libernetes controllers"

[package.metadata.li]
github_repo = "libernetes"
import_name = "watch"
min_lic = "0.1.0"
maintainer = "li-langverse"
pkg_id = "PKG-li-watch"
