[package]
name = "li-assets"
version = "0.1.0"
edition = "2026"
license = "Apache-2.0 OR MIT"
description = "Li package li-assets"

[dependencies]
li-scene = { path = "../li-scene" }

[package.metadata.li]
github_repo = "li-assets"
import_name = "assets"
min_lic = "0.1.0"
maintainer = "li-langverse"
pkg_id = "PKG-li-assets"

[package.repository]
url = "https://github.com/li-langverse/li-assets"
documentation = "https://li-langverse.github.io/li-language/ecosystem/li-assets/"
changelog = "https://github.com/li-langverse/li-assets/blob/main/CHANGELOG.md"
