[package]
name = "player"
version = "0.1.0"
edition = "2026"
license = "Apache-2.0 OR MIT"
description = "Game client and publish shell (PH-GD-7, MMO)"

[dependencies]
# path = { path = "../other" }   # lip 8b+
# registry = "1.0.0"             # lip 8d+

[package.metadata.li]
github_repo = "player"
import_name = "player"
min_lic = "0.1.0"
maintainer = "li-langverse"
pkg_id = "PKG-player"

[package.repository]
url = "https://github.com/li-langverse/player"
documentation = "https://li-langverse.github.io/li-language/ecosystem/player/"
changelog = "https://github.com/li-langverse/player/blob/main/CHANGELOG.md"
