import Lake
open Lake DSL

package liSemantics where
  leanOptions := #[⟨`autoImplicit, false⟩]

@[default_target]
lean_lib LiSemantics where
  roots := #[`Core]

/-- Generated by lic build (build/generated/AutoVC.lean). Built when present. -/
lean_lib AutoVC where
  srcDir := "../../build/generated"
  roots := #[`AutoVC]
