[package]
name = "li-std-numerics"
version = "0.1.0"
edition = "2026"
license = "Apache-2.0 OR MIT"
description = "Li package li-std-numerics"

[dependencies]
li-std-math = { path = "../li-std-math" }
# registry = "1.0.0"             # lip 8d+

[package.metadata.li]
import_name = "math.numerics"
min_lic = "0.1.0"
maintainer = "li-langverse"
pkg_id = "PKG-li-std-numerics"

[package.repository]
url = "https://github.com/li-langverse/li-std-numerics"
documentation = "https://li-langverse.github.io/li-language/ecosystem/li-std-numerics/"
changelog = "https://github.com/li-langverse/li-std-numerics/blob/main/CHANGELOG.md"
