#!/usr/bin/env python3
"""Sync proof-db/erdos/register.json → erdos-register.toml catalog entries (E-{number})."""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]
REGISTER = ROOT / "proof-db" / "erdos" / "register.json"
CATALOG = ROOT / "docs" / "verification" / "proof-database" / "entries" / "erdos-register.toml"

PROOF_STATUS = {"open": "open", "proved": "target", "target": "open", "disputed": "open"}
SPECIMENS = ROOT / "proof-db" / "erdos" / "specimens"


def git_head(short: int = 8) -> str:
    try:
        h = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True, stderr=subprocess.DEVNULL
        ).strip()
        return h[:short] if short else h
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def load_register(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    problems = data.get("problems")
    if not isinstance(problems, list):
        raise SystemExit(f"{path}: missing problems[]")
    return sorted(problems, key=lambda r: int(r["number"]))


def row_to_entry(row: dict[str, Any], commit: str) -> dict[str, Any]:
    n = int(row["number"])
    erdos_status = row.get("erdos_status", "open")
    tags = row.get("tags") or []
    entry: dict[str, Any] = {
        "id": f"E-{n}",
        "kind": "target",
        "field": "erdos",
        "statement": row["statement"].strip(),
        "proof_status": PROOF_STATUS.get(erdos_status, "open"),
        "erdos_number": n,
        "erdos_status": erdos_status,
        "priority_tier": row["priority_tier"],
        "tags": tags,
        "gap_id": "G-erdos",
        "gap_kind": "proof_gap",
        "lean_module": "proof-db/erdos/register.json",
        "register_source": "proof-db/erdos/register.json",
        "last_verified_lic_commit": commit,
    }
    url = row.get("external_url")
    if url:
        entry["external_url"] = url
    specimen = SPECIMENS / f"E-{n}.li"
    if specimen.is_file():
        entry["li_specimen"] = specimen.relative_to(ROOT).as_posix()
    return entry


def format_toml_value(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, list):
        inner = ", ".join(f'"{x}"' for x in v)
        return f"[{inner}]"
    s = str(v).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def render_catalog(entries: list[dict[str, Any]], version: int = 1) -> str:
    lines = [f"version = {version}", "", "# Generated by proof-db/erdos/scripts/erdos_sync_catalog.py", ""]
    for e in entries:
        lines.append("[[entry]]")
        for key in (
            "id",
            "kind",
            "field",
            "statement",
            "proof_status",
            "erdos_number",
            "erdos_status",
            "priority_tier",
            "tags",
            "gap_id",
            "gap_kind",
            "lean_module",
            "li_specimen",
            "register_source",
            "external_url",
            "last_verified_lic_commit",
        ):
            if key in e:
                lines.append(f"{key} = {format_toml_value(e[key])}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def merge_existing(
    new_entries: list[dict[str, Any]], catalog_path: Path
) -> list[dict[str, Any]]:
    """Preserve manual rows in catalog whose ids are not in the sync batch."""
    if not catalog_path.is_file():
        return new_entries
    try:
        import tomllib
    except ImportError:
        import tomli as tomllib  # type: ignore

    old = tomllib.loads(catalog_path.read_text(encoding="utf-8"))
    old_rows = old.get("entry") or []
    if not isinstance(old_rows, list):
        old_rows = [old_rows] if old_rows else []
    new_ids = {e["id"] for e in new_entries}
    kept = [r for r in old_rows if isinstance(r, dict) and r.get("id") not in new_ids]
    return new_entries + kept


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--register", type=Path, default=REGISTER, help="register.json path")
    ap.add_argument("--catalog", type=Path, default=CATALOG, help="output TOML path")
    ap.add_argument("--limit", type=int, default=0, help="sync first N problems by number (0 = all)")
    ap.add_argument("--dry-run", action="store_true", help="print path and count only")
    ap.add_argument("--merge", action="store_true", help="keep catalog rows not in this sync batch")
    args = ap.parse_args()

    rows = load_register(args.register)
    if args.limit > 0:
        rows = rows[: args.limit]

    commit = git_head()
    entries = [row_to_entry(r, commit) for r in rows]
    if args.merge:
        entries = merge_existing(entries, args.catalog)

    if args.dry_run:
        print(f"would write {len(entries)} entries to {args.catalog}")
        return 0

    args.catalog.parent.mkdir(parents=True, exist_ok=True)
    args.catalog.write_text(render_catalog(entries), encoding="utf-8")
    print(f"wrote {len(entries)} entries to {args.catalog}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
