#!/usr/bin/env python3
"""Generate packages/li-ui icon atlas bitmap data from embedded 8×8 dock glyphs (SVG-inspired)."""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "packages/li-ui/src/icon_atlas_data.li"
ATLAS = ROOT / "packages/li-ui/src/icon_atlas.li"
LIB = ROOT / "packages/li-ui/src/lib.li"
BEGIN = "# BEGIN icon-atlas-generated (scripts/build-icon-atlas.py)"
END = "# END icon-atlas-generated"

# Order matches studio_icon_token_id_* and dock slots 0..4
DOCK_ICONS: list[tuple[str, list[int]]] = [
    (
        "dock_scene",
        [
            0b00111100,
            0b01111110,
            0b11100111,
            0b11100111,
            0b11100111,
            0b11100111,
            0b01111110,
            0b00111100,
        ],
    ),
    (
        "dock_assets",
        [
            0b00000000,
            0b00111100,
            0b01111110,
            0b01111110,
            0b01111110,
            0b01111110,
            0b01111110,
            0b00111100,
        ],
    ),
    (
        "dock_sim",
        [
            0b00011000,
            0b00011000,
            0b00011000,
            0b00011000,
            0b01111110,
            0b11111111,
            0b00000000,
            0b00000000,
        ],
    ),
    (
        "dock_timeline",
        [
            0b00111100,
            0b01111110,
            0b01100110,
            0b01100110,
            0b01100110,
            0b01111110,
            0b00111100,
            0b00000000,
        ],
    ),
    (
        "dock_settings",
        [
            0b00011000,
            0b00111100,
            0b01111110,
            0b11111111,
            0b01111110,
            0b00111100,
            0b00011000,
            0b00000000,
        ],
    ),
]


def emit_lookup(name: str, rows: list[list[int]]) -> str:
    lines = [
        f"def {name}(slot: int, row: int) -> int",
        "  requires slot >= 0",
        "  requires slot < icon_atlas_slot_count()",
        "  requires row >= 0",
        "  requires row < icon_atlas_cell_px()",
        "  decreases slot",
        "=",
    ]
    for slot, icon_rows in enumerate(rows):
        lines.append(f"  if slot == {slot}:")
        for row_idx, bits in enumerate(icon_rows):
            lines.append(f"    if row == {row_idx}:")
            lines.append(f"      return {bits}")
    lines.append("  return 0")
    lines.append("")
    return "\n".join(lines)


def checksum(rows: list[list[int]]) -> int:
    h = hashlib.sha256()
    for icon in rows:
        for r in icon:
            h.update(bytes([r & 0xFF]))
    return int.from_bytes(h.digest()[:4], "big") & 0x7FFFFFFF


def generate_data() -> str:
    table = [icon[1] for icon in DOCK_ICONS]
    cs = checksum(table)
    header = "# Generated by scripts/build-icon-atlas.py — do not edit by hand."
    parts = [
        header,
        emit_lookup("icon_atlas_data_row", table),
        "def icon_atlas_data_checksum() -> int",
        "  requires true",
        f"  ensures result == {cs}",
        "  decreases 0",
        "=",
        f"  return {cs}",
        "",
    ]
    return "\n".join(parts)


def mirror_into_lib(data_li: str) -> None:
    atlas_src = ATLAS.read_text(encoding="utf-8").strip()
    block = "\n".join(
        [
            "",
            BEGIN,
            "# Mirrored for `import ui` — edit src/icon_atlas.li + regenerate.",
            atlas_src,
            "",
            data_li.strip(),
            END,
            "",
        ]
    )
    text = LIB.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        pre = text.split(BEGIN)[0].rstrip()
        post = text.split(END, 1)[1].lstrip()
        LIB.write_text(pre + block + post, encoding="utf-8")
    else:
        LIB.write_text(text.rstrip() + block, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    content = generate_data()
    if args.verify:
        if not OUT.is_file():
            print(f"FAIL: missing {OUT}", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != content:
            print(f"FAIL: stale {OUT} — run python3 scripts/build-icon-atlas.py", file=sys.stderr)
            return 1
        if BEGIN not in LIB.read_text(encoding="utf-8"):
            print(f"FAIL: {LIB.name} missing icon atlas mirror", file=sys.stderr)
            return 1
        print("build-icon-atlas: ok")
        return 0
    OUT.write_text(content, encoding="utf-8")
    mirror_into_lib(content)
    print(f"Wrote {OUT.name} and mirrored into {LIB.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
