#!/usr/bin/env bash
# Idempotent Cloud Agent / fresh-VM bootstrap — LLVM 22 + lic build.
# Point Cursor Cloud "install script" at this file (or run once per VM).
#
# Usage:
#   bash /agent/repos/lic/scripts/cloud-vm-bootstrap.sh
#   LI_CLOUD_SKIP_BUILD=1 bash ...   # apt/llvm only
#   LI_CLOUD_SKIP_BENCHMARKS=1 bash ...  # skip dashboard npm ci
set -euo pipefail

LIC_ROOT="${LIC_ROOT:-/agent/repos/lic}"
BENCHMARKS_ROOT="${BENCHMARKS_ROOT:-/agent/repos/benchmarks}"
LLVM_VER="${LI_LLVM_MAJOR:-22}"

echo "==> Li cloud VM bootstrap (LLVM ${LLVM_VER})"

if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
  export DEBIAN_FRONTEND=noninteractive
  export LI_LLVM_MAJOR="$LLVM_VER"
  bash "$LIC_ROOT/scripts/ci-install-llvm.sh"
else
  if ! command -v "clang-${LLVM_VER}" >/dev/null 2>&1; then
    if [[ -f "$LIC_ROOT/scripts/ci-install-llvm.sh" ]] && command -v sudo >/dev/null 2>&1; then
      echo "==> installing LLVM ${LLVM_VER} (sudo)"
      sudo LI_LLVM_MAJOR="$LLVM_VER" bash "$LIC_ROOT/scripts/ci-install-llvm.sh"
    else
      echo "clang-${LLVM_VER} missing; re-run with sudo or pre-install LLVM ${LLVM_VER}" >&2
      exit 1
    fi
  fi
fi

# shellcheck source=llvm-env.sh
source "$LIC_ROOT/scripts/llvm-env.sh"
if ! li_detect_llvm_dir; then
  li_llvm_install_hint
  exit 1
fi
li_detect_compilers
export LLVM_DIR CC CXX LI_LLVM_MAJOR LI_REPO_ROOT="$LIC_ROOT" LIC_ROOT="$LIC_ROOT"

mkdir -p "${HOME}/.config/environment.d"
cat >"${HOME}/.config/environment.d/99-li-cloud.conf" <<EOF
# Generated by scripts/cloud-vm-bootstrap.sh — LLVM ${LLVM_VER} org pin
LI_LLVM_MAJOR=${LLVM_VER}
LLVM_DIR=${LLVM_DIR}
CC=${CC}
CXX=${CXX}
LI_REPO_ROOT=${LIC_ROOT}
LIC_ROOT=${LIC_ROOT}
PATH=${PATH}
EOF
echo "==> wrote ${HOME}/.config/environment.d/99-li-cloud.conf"

if [[ "${LI_CLOUD_SKIP_BUILD:-0}" != "1" ]]; then
  echo "==> build lic"
  (cd "$LIC_ROOT" && ./scripts/build.sh)
  echo "==> lic: $LIC_ROOT/build/compiler/lic/lic"
  "$LIC_ROOT/build/compiler/lic/lic" --version 2>/dev/null || true
fi

if [[ "${LI_CLOUD_SKIP_BENCHMARKS:-0}" != "1" ]]; then
  dash=""
  if [[ -f "$BENCHMARKS_ROOT/dashboard-next/package.json" ]]; then
    dash="$BENCHMARKS_ROOT/dashboard-next"
  elif [[ -f "$BENCHMARKS_ROOT/dashboard/package.json" ]]; then
    dash="$BENCHMARKS_ROOT/dashboard"
  fi
  if [[ -n "$dash" ]] && command -v npm >/dev/null 2>&1; then
    echo "==> benchmarks dashboard npm ci ($dash)"
    (cd "$dash" && npm ci)
  elif [[ -z "$dash" ]]; then
    echo "==> skip benchmarks dashboard (no dashboard-next/ dashboard package.json)"
  else
    echo "==> skip benchmarks dashboard (npm not installed)"
  fi
fi

if [[ "${LI_CLOUD_SKIP_PYTEST:-0}" != "1" ]] && command -v pip3 >/dev/null 2>&1; then
  pip3 install -q pytest 2>/dev/null || pip3 install pytest
fi

echo "==> cloud-vm-bootstrap OK (LLVM ${LI_LLVM_MAJOR} at ${LLVM_DIR})"
