#!/usr/bin/env bash
# Install weekly user systemd timer for benchmarks ecosystem-quality-grade.py
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LANGVERSE="$(cd "$ROOT/.." && pwd)"
BENCH="$LANGVERSE/benchmarks"
ENV_FILE="${LI_CURSOR_ENV_FILE:-$HOME/Documents/Cursor/.env}"
SERVICE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT_SERVICE="li-ecosystem-quality-grade.service"
UNIT_TIMER="li-ecosystem-quality-grade.timer"
LOG_DIR="$BENCH/data/ecosystem-quality-grade"
mkdir -p "$LOG_DIR" "$SERVICE_DIR"
chmod +x "$BENCH/scripts/ecosystem-quality-grade.py" 2>/dev/null || true

cat >"$SERVICE_DIR/${UNIT_SERVICE}" <<EOF
# Generated by ecosystem-quality-grade-systemd.sh
[Unit]
Description=Li ecosystem quality scorecard (deterministic)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
WorkingDirectory=$BENCH
Environment=HOME=$HOME
Environment=LI_CURSOR_ENV_FILE=$ENV_FILE
Environment=LI_CURSOR_AGENTS_ROOT=$LANGVERSE/li-cursor-agents
Environment=LIC_ROOT=$ROOT
ExecStart=/usr/bin/env python3 scripts/ecosystem-quality-grade.py
StandardOutput=append:${LOG_DIR}/grade.log
StandardError=append:${LOG_DIR}/grade.log

[Install]
WantedBy=default.target
EOF

cat >"$SERVICE_DIR/${UNIT_TIMER}" <<EOF
# Generated by ecosystem-quality-grade-systemd.sh — weekly Sunday 06:00 local
[Unit]
Description=Weekly Li ecosystem quality grade

[Timer]
OnCalendar=Sun *-*-* 06:00:00
Persistent=true
Unit=${UNIT_SERVICE}

[Install]
WantedBy=timers.target
EOF

if command -v loginctl >/dev/null 2>&1; then
  loginctl enable-linger "$(whoami)" 2>/dev/null || true
fi

systemctl --user daemon-reload
systemctl --user enable --now "${UNIT_TIMER}"
echo "Installed ${UNIT_TIMER} → ${UNIT_SERVICE}"
echo "  log: ${LOG_DIR}/grade.log"
echo "  report: ${BENCH}/data/latest/ecosystem-quality-report.json"
systemctl --user list-timers "${UNIT_TIMER}" --no-pager 2>/dev/null | head -5 || true
