#!/usr/bin/env bash
# Generate agent entry artifacts from docs/ecosystem/li-agent-manifest.toml (stub).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MANIFEST="$ROOT/docs/ecosystem/li-agent-manifest.toml"
OUT_JSON="$ROOT/li-agent.json"
FRAGMENT="$ROOT/.cursor/AGENTS.generated.md"

if [[ ! -f "$MANIFEST" ]]; then
  echo "gen-li-agent-manifest: missing $MANIFEST" >&2
  exit 1
fi

cat >"$OUT_JSON" <<EOF
{
  "name": "li-lic",
  "version": 1,
  "source": "docs/ecosystem/li-agent-manifest.toml",
  "commands": {
    "check": "lic check",
    "check_json": "lic check --format=json",
    "diagnose": "lic diagnose",
    "build": "lic build",
    "verify": "lic verify",
    "tests": "./li-tests/run_all.sh"
  },
  "diagnostics": {
    "schema": "docs/schemas/diagnostic-v1.json",
    "format_flag": "--format=json"
  }
}
EOF

cat >"$FRAGMENT" <<'EOF'
<!-- Generated by scripts/gen-li-agent-manifest.sh — do not edit by hand -->

## Li agent entry (generated)

- **Check (human):** `lic check <file>`
- **Check (JSON):** `lic check <file> --format=json`
- **Diagnose:** `lic diagnose <file>`
- **Tests:** `./li-tests/run_all.sh`
- **Schema:** `docs/schemas/diagnostic-v1.json`
- **Fix stub:** `./scripts/lic-fix-suggest.sh`

Provability wins: `lic build` is the proof certificate; JSON check is IDE/agent speed only.
EOF

echo "gen-li-agent-manifest: wrote $OUT_JSON and $FRAGMENT"
