#!/usr/bin/env bash
# Install a user systemd unit for a goal-directed plan loop (survives reboot).
# Usage:
#   ./scripts/install-goal-plan-loop-systemd.sh sim-algo
#   ./scripts/install-goal-plan-loop-systemd.sh --all
#   ./scripts/install-goal-plan-loop-systemd.sh --list
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${LI_CURSOR_ENV_FILE:-$HOME/Documents/Cursor/.env}"
SERVICE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"

plan_def() {
  case "$1" in
    sim-algo)
      echo "li-sim-algo-plan-loop|scripts/sim-plan-loop-systemd.sh|data/sim-plan-loop"
      ;;
    httpd)
      echo "li-httpd-plan-loop|scripts/httpd-plan-loop-systemd.sh|data/httpd-plan-loop"
      ;;
    compiler-studio)
      echo "li-compiler-studio-plan-loop|scripts/compiler-studio-plan-loop-systemd.sh|data/compiler-studio-plan-loop"
      ;;
    studio-ui-ux)
      echo "li-studio-ui-ux-plan-loop|scripts/studio-ui-ux-plan-loop-systemd.sh|data/studio-ui-ux-plan-loop"
      ;;
    *)
      return 1
      ;;
  esac
}

install_one() {
  local id="$1"
  local line
  line="$(plan_def "$id")" || { echo "unknown plan id: $id" >&2; return 1; }
  IFS='|' read -r unit wrapper data_rel <<<"$line"
  local wrapper_path="$ROOT/$wrapper"
  local data_dir="$ROOT/$data_rel"
  chmod +x "$wrapper_path" "$ROOT/scripts/lib/goal-plan-systemd-wrapper.sh" 2>/dev/null || true
  mkdir -p "$data_dir" "$SERVICE_DIR"

  cat >"$SERVICE_DIR/${unit}.service" <<EOF
# Generated by install-goal-plan-loop-systemd.sh ($id)
[Unit]
Description=Li goal plan loop: $id (survives reboot)
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=600
StartLimitBurst=10

[Service]
Type=simple
WorkingDirectory=$ROOT
Environment=HOME=$HOME
Environment=LI_CURSOR_ENV_FILE=$ENV_FILE
Environment=LI_CURSOR_AGENTS_ROOT=$ROOT/../li-cursor-agents
Environment=LIC_ROOT=$ROOT
ExecStart=$wrapper_path
Restart=on-failure
RestartSec=90
SuccessExitStatus=0
KillMode=control-group
TimeoutStopSec=300
StandardOutput=append:${data_dir}/systemd.log
StandardError=append:${data_dir}/systemd.log

[Install]
WantedBy=default.target
EOF

  systemctl --user daemon-reload
  systemctl --user enable "${unit}.service"
  systemctl --user restart "${unit}.service" || systemctl --user start "${unit}.service"
  echo "Installed ${unit}.service (id=$id)"
  echo "  log: ${data_dir}/systemd.log"
  systemctl --user status "${unit}.service" --no-pager -l 2>/dev/null | head -12 || true
}

list_plans() {
  echo "Goal plan loops:"
  echo "  sim-algo          — simulation algorithms (cursor/sim-algo-plan-loop)"
  echo "  httpd             — li-httpd master plan"
  echo "  compiler-studio   — compiler / studio plan"
  echo "  studio-ui-ux      — Studio UI/UX plan"
}

if [[ "${1:-}" == "--list" ]]; then
  list_plans
  exit 0
fi

if [[ "${1:-}" == "--all" ]]; then
  if command -v loginctl >/dev/null 2>&1; then
    loginctl enable-linger "$(whoami)" 2>/dev/null || true
  fi
  for id in sim-algo httpd compiler-studio studio-ui-ux; do
    install_one "$id" || true
    echo ""
  done
  exit 0
fi

if [[ -z "${1:-}" ]]; then
  echo "usage: $0 <plan-id> | --all | --list" >&2
  exit 2
fi

if command -v loginctl >/dev/null 2>&1; then
  loginctl enable-linger "$(whoami)" 2>/dev/null || true
fi

# sim cron
if [[ "$1" == "sim-algo" && -x "$ROOT/scripts/sim-plan-install-cron.sh" ]]; then
  "$ROOT/scripts/sim-plan-install-cron.sh" 2>/dev/null || true
fi
if [[ "$1" == "studio-ui-ux" && -x "$ROOT/scripts/studio-ui-ux-install-cron.sh" ]]; then
  "$ROOT/scripts/studio-ui-ux-install-cron.sh" 2>/dev/null || true
fi

install_one "$1"
