#!/usr/bin/env bash
# Install a user systemd unit for a goal-directed plan loop (survives reboot).
# Usage:
#   ./scripts/install-goal-plan-loop-systemd.sh sim-algo
#   ./scripts/install-goal-plan-loop-systemd.sh --all
#   ./scripts/install-goal-plan-loop-systemd.sh --list
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${LI_CURSOR_ENV_FILE:-$HOME/Documents/Cursor/.env}"
SERVICE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"

# plan_def: unit|wrapper|data_dir_relative_to_ROOT|extra Environment lines (optional, pipe-separated)
plan_def() {
  case "$1" in
    sim-algo)
      echo "li-sim-algo-plan-loop|scripts/sim-plan-loop-systemd.sh|../lic-worktrees/sim-algo/data/sim-plan-loop"
      ;;
    httpd)
      echo "li-httpd-plan-loop|scripts/httpd-plan-loop-systemd.sh|data/httpd-plan-loop"
      ;;
    compiler-studio)
      echo "li-compiler-studio-plan-loop|scripts/compiler-studio-plan-loop-systemd.sh|../lic-worktrees/compiler-studio/data/compiler-studio-plan-loop"
      ;;
    studio-ui-ux)
      echo "li-studio-ui-ux-plan-loop|scripts/studio-ui-ux-plan-loop-systemd.sh|../lic-studio-ui/data/studio-ui-ux-plan-loop|LI_CONTROL_PLANE_STORE=disk|LI_STACK_SKIP_SUPABASE=1|LI_EXPORT_DISK_CACHE=1"
      ;;
    sim-md-research)
      echo "li-sim-md-research-plan-loop|scripts/sim-md-research-plan-loop-systemd.sh|../lic-worktrees/sim-md-research/data/sim-md-research-loop|SIM_RESEARCH_VERTICAL=md"
      ;;
    sim-chem-research)
      echo "li-sim-chem-research-plan-loop|scripts/sim-chem-research-plan-loop-systemd.sh|../lic-worktrees/sim-chem-research/data/sim-chem-research-loop|SIM_RESEARCH_VERTICAL=chem"
      ;;
    *)
      return 1
      ;;
  esac
}

install_one() {
  local id="$1"
  local line
  line="$(plan_def "$id")" || { echo "unknown plan id: $id" >&2; return 1; }
  local -a parts=()
  IFS='|' read -ra parts <<<"$line"
  local unit="${parts[0]}"
  local wrapper="${parts[1]}"
  local data_rel="${parts[2]}"
  local wrapper_path="$ROOT/$wrapper"
  local data_dir
  if [[ "$data_rel" == /* ]]; then
    data_dir="$data_rel"
  else
    data_dir="$(cd "$ROOT" && cd "$(dirname "$data_rel")" 2>/dev/null && pwd)/$(basename "$data_rel")"
  fi
  chmod +x "$wrapper_path" "$ROOT/scripts/lib/goal-plan-systemd-wrapper.sh" 2>/dev/null || true
  chmod +x "$ROOT/scripts/"*-plan-loop-systemd.sh 2>/dev/null || true
  mkdir -p "$data_dir" "$SERVICE_DIR"

  local extra_env=""
  local i
  for ((i = 3; i < ${#parts[@]}; i++)); do
    extra_env+=$'\n'"Environment=${parts[$i]}"
  done

  cat >"$SERVICE_DIR/${unit}.service" <<EOF
# Generated by install-goal-plan-loop-systemd.sh ($id) — goal-plan-systemd-wrapper.sh
[Unit]
Description=Li goal plan loop: $id (survives reboot)
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=600
StartLimitBurst=10

[Service]
Type=simple
WorkingDirectory=$ROOT
Environment=HOME=$HOME
Environment=LI_CURSOR_ENV_FILE=$ENV_FILE
Environment=LI_CURSOR_AGENTS_ROOT=$ROOT/../li-cursor-agents
Environment=LIC_ROOT=$ROOT
Environment=LI_CONTROL_PLANE_STORE=disk
Environment=LI_AGENT_INSTALL_DEPS=${LI_AGENT_INSTALL_DEPS:-0}${extra_env}
ExecStart=$wrapper_path
Restart=on-failure
RestartSec=90
SuccessExitStatus=0
KillMode=control-group
TimeoutStopSec=300
StandardOutput=append:${data_dir}/systemd.log
StandardError=append:${data_dir}/systemd.log

[Install]
WantedBy=default.target
EOF

  systemctl --user daemon-reload
  systemctl --user enable "${unit}.service"
  systemctl --user restart "${unit}.service" || systemctl --user start "${unit}.service"
  echo "Installed ${unit}.service (id=$id)"
  echo "  log: ${data_dir}/systemd.log"
  systemctl --user status "${unit}.service" --no-pager -l 2>/dev/null | head -12 || true
}

list_plans() {
  echo "Goal plan loops (shared supervisor: scripts/lib/goal-plan-systemd-wrapper.sh):"
  echo "  sim-algo          — lic-worktrees/sim-algo"
  echo "  httpd             — lic (cursor/httpd-plan-continue)"
  echo "  compiler-studio   — lic-worktrees/compiler-studio"
  echo "  studio-ui-ux      — lic-studio-ui"
  echo "  sim-md-research   — lic-worktrees/sim-md-research (numerics_researcher)"
  echo "  sim-chem-research — lic-worktrees/sim-chem-research (numerics_researcher)"
  echo ""
  echo "Install all: $0 --all"
}

if [[ "${1:-}" == "--list" ]]; then
  list_plans
  exit 0
fi

if [[ "${1:-}" == "--all" ]]; then
  if command -v loginctl >/dev/null 2>&1; then
    loginctl enable-linger "$(whoami)" 2>/dev/null || true
  fi
  for id in sim-algo sim-md-research sim-chem-research httpd compiler-studio studio-ui-ux; do
    install_one "$id" || true
    echo ""
  done
  exit 0
fi

if [[ -z "${1:-}" ]]; then
  echo "usage: $0 <plan-id> | --all | --list" >&2
  exit 2
fi

if command -v loginctl >/dev/null 2>&1; then
  loginctl enable-linger "$(whoami)" 2>/dev/null || true
fi

# sim cron
if [[ "$1" == "sim-algo" && -x "$ROOT/scripts/sim-plan-install-cron.sh" ]]; then
  "$ROOT/scripts/sim-plan-install-cron.sh" 2>/dev/null || true
fi
if [[ "$1" == "studio-ui-ux" && -x "$ROOT/scripts/studio-ui-ux-install-cron.sh" ]]; then
  "$ROOT/scripts/studio-ui-ux-install-cron.sh" 2>/dev/null || true
fi

install_one "$1"
