#!/usr/bin/env bash
# Install user systemd unit + linger so Studio UI/UX loop survives reboot.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
UNIT_NAME="li-studio-ui-ux-plan-loop"
SERVICE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
WRAPPER="$ROOT/scripts/studio-ui-ux-plan-loop-systemd.sh"
ENV_FILE="${LI_CURSOR_ENV_FILE:-$HOME/Documents/Cursor/.env}"

chmod +x "$WRAPPER" "$ROOT/scripts/studio-ui-ux-run-until-done.sh"

mkdir -p "$SERVICE_DIR" "${ROOT}/data/studio-ui-ux-plan-loop"

cat >"$SERVICE_DIR/${UNIT_NAME}.service" <<EOF
# Generated by install-studio-ui-ux-plan-loop-systemd.sh
[Unit]
Description=Li Studio UI/UX plan loop (studio_ui_ux_builder; survives reboot)
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=600
StartLimitBurst=10

[Service]
Type=simple
WorkingDirectory=$ROOT
Environment=HOME=$HOME
Environment=LI_CURSOR_ENV_FILE=$ENV_FILE
Environment=LI_CURSOR_AGENTS_ROOT=$ROOT/../li-cursor-agents
ExecStart=$WRAPPER
Restart=on-failure
RestartSec=90
SuccessExitStatus=0
KillMode=control-group
TimeoutStopSec=300
StandardOutput=append:${ROOT}/data/studio-ui-ux-plan-loop/systemd.log
StandardError=append:${ROOT}/data/studio-ui-ux-plan-loop/systemd.log

[Install]
WantedBy=default.target
EOF

# Daily report cron (08:00) if not already installed
"$ROOT/scripts/studio-ui-ux-install-cron.sh" 2>/dev/null || true

# User services must run when logged out
if command -v loginctl >/dev/null 2>&1; then
  loginctl enable-linger "$(whoami)" 2>/dev/null || true
fi

systemctl --user daemon-reload
systemctl --user enable "${UNIT_NAME}.service"
systemctl --user restart "${UNIT_NAME}.service" || systemctl --user start "${UNIT_NAME}.service"

echo ""
echo "Installed: ${UNIT_NAME}.service"
echo "  ExecStart: $WRAPPER"
echo "  Log:       ${ROOT}/data/studio-ui-ux-plan-loop/systemd.log"
echo "  Runner:    ${ROOT}/data/studio-ui-ux-plan-loop/runner.log"
echo ""
systemctl --user status "${UNIT_NAME}.service" --no-pager -l 2>/dev/null | head -15 || true
echo ""
echo "Stop:    systemctl --user stop ${UNIT_NAME}"
echo "Disable: touch ${ROOT}/data/studio-ui-ux-plan-loop/DISABLE_AUTOSTART && systemctl --user stop ${UNIT_NAME}"
echo "Linger:  $(loginctl show-user "$(whoami)" -p Linger 2>/dev/null || echo 'check loginctl')"
