#!/usr/bin/env bash
# Install user systemd units so compiler-studio + httpd plan loops resume after reboot.
#
# Usage:
#   ./scripts/install-plan-loop-systemd.sh              # install + enable + start both
#   ./scripts/install-plan-loop-systemd.sh --install-only
#   ./scripts/install-plan-loop-systemd.sh --compiler-only
#   ./scripts/install-plan-loop-systemd.sh --disable    # stop + disable autostart
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
USER_NAME="$(id -un)"
HOME_DIR="${HOME}"
UNIT_DIR="${HOME_DIR}/.config/systemd/user"
CURSOR_ENV="${LI_CURSOR_ENV_FILE:-${HOME_DIR}/Documents/Cursor/.env}"

INSTALL_ONLY=0
DISABLE=0
SKIP_COMPILER=0
SKIP_HTTPD=0
START=1
ENABLE=1

for arg in "$@"; do
  case "$arg" in
    --install-only) INSTALL_ONLY=1; START=0 ;;
    --disable) DISABLE=1; START=0; ENABLE=0 ;;
    --compiler-only) SKIP_HTTPD=1 ;;
    --httpd-only) SKIP_COMPILER=1 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
  esac
done

write_unit() {
  local name="$1"
  local exec="$2"
  local unit="${UNIT_DIR}/${name}.service"
  mkdir -p "$UNIT_DIR"
  cat >"$unit" <<EOF
# Generated by install-plan-loop-systemd.sh — do not edit by hand.
[Unit]
Description=Li ${name} autonomous plan loop (resume after reboot until deadline)
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=600
StartLimitBurst=10

[Service]
Type=simple
WorkingDirectory=${ROOT}
Environment=HOME=${HOME_DIR}
Environment=LI_CURSOR_ENV_FILE=${CURSOR_ENV}
ExecStart=${exec}
Restart=on-failure
RestartSec=90
# Exit 0 when deadline passed or DISABLE_AUTOSTART — do not treat as failure loop
SuccessExitStatus=0
KillMode=control-group
TimeoutStopSec=300

[Install]
WantedBy=default.target
EOF
  echo "  wrote $unit"
}

if [[ "$DISABLE" == "1" ]]; then
  systemctl --user stop li-compiler-studio-plan-loop.service 2>/dev/null || true
  systemctl --user stop li-httpd-plan-loop.service 2>/dev/null || true
  systemctl --user disable li-compiler-studio-plan-loop.service 2>/dev/null || true
  systemctl --user disable li-httpd-plan-loop.service 2>/dev/null || true
  touch "$ROOT/data/compiler-studio-plan-loop/DISABLE_AUTOSTART" 2>/dev/null || mkdir -p "$ROOT/data/compiler-studio-plan-loop" && touch "$ROOT/data/compiler-studio-plan-loop/DISABLE_AUTOSTART"
  touch "$ROOT/data/httpd-plan-loop/DISABLE_AUTOSTART" 2>/dev/null || mkdir -p "$ROOT/data/httpd-plan-loop" && touch "$ROOT/data/httpd-plan-loop/DISABLE_AUTOSTART"
  echo "Disabled plan-loop systemd units and touched DISABLE_AUTOSTART files."
  exit 0
fi

chmod +x "$ROOT/scripts/compiler-studio-plan-loop-systemd.sh"
chmod +x "$ROOT/scripts/httpd-plan-loop-systemd.sh"
chmod +x "$ROOT/scripts/compiler-studio-plan-overnight.sh" 2>/dev/null || true
chmod +x "$ROOT/scripts/httpd-plan-overnight.sh" 2>/dev/null || true

echo "==> install-plan-loop-systemd (user=${USER_NAME})"
echo "    lic=$ROOT"

if [[ "$SKIP_COMPILER" != "1" ]]; then
  write_unit "li-compiler-studio-plan-loop" "${ROOT}/scripts/compiler-studio-plan-loop-systemd.sh"
fi
if [[ "$SKIP_HTTPD" != "1" ]]; then
  write_unit "li-httpd-plan-loop" "${ROOT}/scripts/httpd-plan-loop-systemd.sh"
fi

# env snippets (used by systemd wrappers)
bash "$ROOT/scripts/compiler-studio-plan-setup.sh" --env-only 2>/dev/null || true
if [[ -f "$ROOT/scripts/httpd-plan-setup.sh" ]]; then
  bash "$ROOT/scripts/httpd-plan-setup.sh" 2>/dev/null | tail -1 >/dev/null || true
fi

if ! command -v systemctl >/dev/null 2>&1; then
  echo "systemctl not found — units written but not enabled" >&2
  exit 0
fi

systemctl --user daemon-reload

if command -v loginctl >/dev/null 2>&1; then
  if loginctl show-user "$USER_NAME" -p Linger 2>/dev/null | grep -q 'Linger=no'; then
    echo "==> enabling linger (user services start at boot without login)"
    loginctl enable-linger "$USER_NAME" || echo "    (loginctl enable-linger failed — run with sudo or as admin)"
  else
    echo "==> linger already enabled for $USER_NAME"
  fi
fi

if [[ "$ENABLE" == "1" ]]; then
  [[ "$SKIP_COMPILER" != "1" ]] && rm -f "$ROOT/data/compiler-studio-plan-loop/DISABLE_AUTOSTART"
  [[ "$SKIP_HTTPD" != "1" ]] && rm -f "$ROOT/data/httpd-plan-loop/DISABLE_AUTOSTART"
  if [[ "$SKIP_COMPILER" != "1" ]]; then
    systemctl --user enable li-compiler-studio-plan-loop.service
  fi
  if [[ "$SKIP_HTTPD" != "1" ]]; then
    systemctl --user enable li-httpd-plan-loop.service
  fi
fi

if [[ "$START" == "1" && "$INSTALL_ONLY" == "0" ]]; then
  if [[ "$SKIP_COMPILER" != "1" ]]; then
    systemctl --user restart li-compiler-studio-plan-loop.service || systemctl --user start li-compiler-studio-plan-loop.service
  fi
  if [[ "$SKIP_HTTPD" != "1" ]]; then
    systemctl --user restart li-httpd-plan-loop.service || systemctl --user start li-httpd-plan-loop.service
  fi
fi

echo ""
echo "Status:"
if [[ "$SKIP_COMPILER" != "1" ]]; then
  systemctl --user status li-compiler-studio-plan-loop.service --no-pager -l 2>/dev/null | head -12 || true
fi
if [[ "$SKIP_HTTPD" != "1" ]]; then
  systemctl --user status li-httpd-plan-loop.service --no-pager -l 2>/dev/null | head -12 || true
fi
echo ""
echo "Logs:"
echo "  journalctl --user -u li-compiler-studio-plan-loop -f"
echo "  journalctl --user -u li-httpd-plan-loop -f"
echo "  tail -f $ROOT/data/compiler-studio-plan-loop/until-deadline-*.log"
echo ""
echo "Stop autostart after weekend:"
echo "  ./scripts/install-plan-loop-systemd.sh --disable"
