#!/usr/bin/env bash
# Reconfigure lic git to use gh credentials (not Cloud Agent x-access-token insteadOf).
# Writes sibling ../.env.github with LI_REPO_ROOT + GH_TOKEN for with-github-env.sh / agent-push.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if ! command -v gh >/dev/null 2>&1; then
  echo "reconfigure-git-origin: install GitHub CLI (gh) first" >&2
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  echo "reconfigure-git-origin: run gh auth login" >&2
  exit 1
fi

echo "reconfigure-git-origin: removing global github.com URL rewrites (cursor[bot] token)…"
while out="$(git config --global --get-regexp '^url\..*\.insteadof$' 2>/dev/null | head -1)" && [[ -n "$out" ]]; do
  key="${out%% *}"
  git config --global --unset-all "$key" || break
done

gh auth setup-git -h github.com

git remote set-url origin https://github.com/li-langverse/lic.git
echo "origin=$(git config --get remote.origin.url)"

ENV="$(cd "$ROOT/.." && pwd)/.env.github"
TOKEN="$(gh auth token)"
umask 077
cat >"$ENV" <<EOF
# Generated by lic/scripts/reconfigure-git-origin.sh — do not commit
export LI_REPO_ROOT=$ROOT
export GH_TOKEN=$TOKEN
export LIC_ROOT=$ROOT
EOF
echo "wrote $ENV (LI_REPO_ROOT=$ROOT)"

if [[ -f "$ROOT/scripts/with-github-env.sh" ]]; then
  echo "reconfigure-git-origin: testing push access…"
  "$ROOT/scripts/with-github-env.sh" gh repo view li-langverse/lic --json nameWithOwner -q .nameWithOwner
fi

echo "reconfigure-git-origin: ok — use ./scripts/agent-push-github.sh or: source ../.env.github && git push -u origin HEAD"
