[package]
name = "li-std-math"
version = "0.1.0"
edition = "2026"
license = "Apache-2.0 OR MIT"
description = "Li package li-std-math"

[dependencies]
li-std-core = { path = "../li-std-core" }

[package.metadata.li]
import_name = "math"
min_lic = "0.1.0"
maintainer = "li-langverse"
pkg_id = "PKG-li-std-math"

[package.repository]
url = "https://github.com/li-langverse/li-std-math"
documentation = "https://li-langverse.github.io/li-language/ecosystem/li-std-math/"
changelog = "https://github.com/li-langverse/li-std-math/blob/main/CHANGELOG.md"
