[package]
name = "li-std-physics-core"
version = "0.1.0"
edition = "2026"
license = "Apache-2.0 OR MIT"
description = "Li package li-std-physics-core"

[dependencies]
li-std-math = { path = "../li-std-math" }
li-std-numerics = { path = "../li-std-numerics" }
# registry = "1.0.0"             # lip 8d+

[package.metadata.li]
min_lic = "0.1.0"
maintainer = "li-langverse"
pkg_id = "PKG-li-std-physics-core"

[package.repository]
url = "https://github.com/li-langverse/li-std-physics-core"
documentation = "https://li-langverse.github.io/li-language/ecosystem/li-std-physics-core/"
changelog = "https://github.com/li-langverse/li-std-physics-core/blob/main/CHANGELOG.md"
