[package]
name = "li-physics-em"
version = "0.1.0"
edition = "2026"
license = "Apache-2.0 OR MIT"
description = "Li package li-physics-em"

[dependencies]
li-physics-core = { path = "../li-physics-core" }
li-math-numerics = { path = "../li-math-numerics" }
# registry = "1.0.0"             # lip 8d+

[package.metadata.li]
github_repo = "li-physics-em"
import_name = "physics.em"
min_lic = "0.1.0"
maintainer = "li-langverse"
pkg_id = "PKG-li-physics-em"

[package.repository]
url = "https://github.com/li-langverse/li-physics-em"
documentation = "https://li-langverse.github.io/li-language/ecosystem/li-physics-em/"
changelog = "https://github.com/li-langverse/li-physics-em/blob/main/CHANGELOG.md"
